name: playwright test
on:
    push:
      branches: [main]

jobs:
    playwrighttest:
      runs-on: ubuntu-latest
      container:
        image: mcr.microsoft.com/playwright:v1.29.1-focal
        env:
          ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}

      steps: 
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Run Test
          run: echo "Start the shopping store apps"
               chmod +x ./shopping-store-linux-amd64
               echo "Install depedencies from lock file"
               npm ci 
               echo "Run Playwright Test"
               npm run test:ci
        - name: Verify Test Report Generation
          run: ls -R test-reports

        - name: Archive Test Reports
          uses: actions/upload-artifact@v4
          with:
            name: test-reports
            path: |
              test-reports/html-report
            if-no-files-found: warn
            include-hidden-files: false
       
