name: playwright test
on:
    push:
    branches: [main]

jobs:
    playwrighttest:
      runs-on: ubuntu-latest
      steps: 
      -name: Checkout repository
       uses: action/checkout@v2
      -name: Say Hello
       run: echo hello 
